[package]
name = "fimi"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dirs = "5.0.1"
serde = "1.0.211"
serde_derive = "1.0.211"
serde_json = "1.0.132"

[lib]
path = "src/lib.rs"
